[package]
name = "cnvrt"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "cnvrt_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
image = { version = "0.25", features = ["jpeg", "png", "webp", "tiff", "bmp", "gif", "ico", "pnm"] }
imageproc = "0.23"
thiserror = "1"
anyhow = "1"
log = "0.4"
env_logger = "0.11"
rayon = "1"
uuid = { version = "1", features = ["v4", "serde"] }
dirs = "5"
rfd = "0.14"
ffmpeg-sidecar = "0.3"
ureq = { version = "3", features = ["json"] }
zip = "0.6"
tar = "0.4"
xz2 = "0.1"
